name: CXX CI(project1)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Configure CMake
      run: |
          cd projects/project1/ 
          mkdir -Force build 
          cmake -B build `
          -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build build --config Release --target project1 --parallel $env:NUMBER_OF_PROCESSORS
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: HelloWorld
        path: build/Release/project1.exe
