name: Android CI-project1

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: main-repo
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build Android APK
      working-directory: main-repo/projects/project1_android
      run: |
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@main
      with:
        name: uniball-game-apk
        path: main-repo/projects/project1_android/app/build/outputs/apk/debug/*.apk
