name: CXX CI(project2)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Configure CMake
      run: |
          cd projects/project2/ 
          mkdir -Force build 
          cmake -B build `
          -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build projects/project2/build --config Release --target project1 --parallel $env:NUMBER_OF_PROCESSORS
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: project2
        path: projects/project2/build/Release/project1.exe
